travis_build.shlanguage: python

python:
  - "3.6"

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

before_install:
 - chmod +x travis_build.sh
 - chmod +x run_pytests.sh

install: ./travis_build.sh

# command to run tests
script:
 - ./run_pytests.sh