 version: '2'
 services:

  ecorest:
    build: .
    expose:
    - "8080"

  nginx:
    # restart: always
    image: funkswing/nginx-uwsgi-python
    ports:
    - "80:80"
    - "443:443"
    links:  # Same as depends_on ecorest, but also sets the hostname at which this service can reach the linked service
    - ecorest:uwsgi  # Nginx.conf can reference "ecorest" service with the hostname 'uwsgi' or 'ecorest'

  # Update for Celery: celery_worker and redis
  celery_worker:
    build: ../celery_qed
    image: stack-celery
    command: # celery worker -A tasks -Q testing -l info
    links:
      - redis
      - ecorest
    environment:
      - REDIS_HOSTNAME=redis
      - DOCKER_HOSTNAME=${HOSTNAME}

  redis:
    image: redis:latest
    hostname: redis
    expose:
      - "6379"
