 version: '2'
 services:
  ecorest:
    build: .
    expose:
    - "7777"
#    volumes:
#    - .:/code
  nginx:
#    restart: always
    image: funkswing/nginx-uwsgi-python
    ports:
    - "80:80"
    - "443:443"
    links:  # Share hostname with ecorest and depends_on ecorest
    - ecorest:uwsgi